### PR TITLE
feat: Add charge port latch lock, #323

### PR DESCRIPTION
**Pull request by InTheDaylight14**
https://github.com/alandtse/tesla/issues/323

Feature working in the dev container. 

There is no option to close the latch with Tesla's API. The car itself handles that. I could not find a way to hid the "lock" feature so I'm having it throw a message in the logs that it cannot be locked. I'm not sure what is best practice in that situation.

### CODE REVIEW

**Comment by alandtse** [comment]
Any idea why it thinks you changed the entire readme? I'd prefer the commit history was accurate.

**Comment by InTheDaylight14** [comment]
I'm not sure why that happened. I can submit another PR

**Comment by alandtse** [comment]
You don't have to close it. Just do a new commit that fixes the changes to the readme so it's only your changes.

**Comment by InTheDaylight14** [comment]
> You don't have to close it. Just do a new commit that fixes the changes to the readme so it's only your changes.

I'll be honest, I don't know how to do that. After some research I tired the ```git restore``` on a version of the readme from the main repository dev branch. It looks like, after committing the restored readme, it is still -1,112 +1,112. Is there a different git command I should be using? I can do more research

**Comment by alandtse** [comment]
@shred86 are you saying we should revert this?

**Comment by shred86** [comment]
Doesn’t really matter to me. It’s calling the same endpoint as the charger port cover entity. I described what’s happening in [this post](https://github.com/alandtse/tesla/issues/285#issuecomment-1287812635) because there is one small “issue” where you can’t use the entity itself to call the cover open if it’s already open, so you have to use the cover.open_cover service. If folks are needing this for an automation, then it’s simple enough to call the cover.open_cover service.

**Comment by InTheDaylight14** [comment]
The cover could be considered closed when the physical door is closed OR when the latch is engaged (The latch actualy says engaged when the door is closed anyway). That way the open door and unlatch functionality is available through the UI for both cases and through one entity. Not sure if that would be confusing to ppl if they are charging and the charge port door is "closed" in the UI.

**Comment by alandtse** [comment]
I don't have a dog in this fight as I don't use this feature at all. If the new convention is to use a cover and people with an issue just have to do a manual service call, I don't really care. However, since @shred86 literally removed this functionality, I need to know whether you think this is something I should revert or not. Otherwise I'll have to deal with the same code getting removed and readded multiple times by different people.

Please decide between the two of you what we're doing here. If it's really separate functionality, we can keep the lock separate.

**Pull request merged**
