### PR TITLE
Expose charge_current_request_max attribute

### PR DESCRIPTION
**Pull request by danielp370**
Hi,

This PR exposes the charge_current_request_max variable now available in teslajsonpy.  

Tested in HA and it presents the expected value. Ran black over changed files :)

Thanks

### CODE REVIEW

**Comment by alandtse** [comment]
It's a bit confusing but the `manifest.json` in the custom_component directory also needs to be updated. That is what HA will read.

The pyproject.yaml is just for development.

**Comment by danielp370** [comment]
First time using poetry - Do I need to push the poetry.lock file as well?

**Comment by alandtse** [comment]
> Do I need to push the poetry.lock file as well?

Yes.

**Comment by alandtse** [comment]
Thanks. There's another feature update in the queue so I'll leave this in dev for a little to see if I can batch them.

**Pull request merged**
