### PR TITLE
fix: vehicles use usable_battery_level to match app

### PR DESCRIPTION
**Pull request by carleeno**
For #359 

This updates the battery sensor for vehicles to use the `usable_battery_level` value so that it matches the Tesla app and in-car display in all weather conditions.

Additionally a `raw_soc` attribute is added to the battery sensor to provide insight into the battery's SOC, which does not change with temperature. This allows for users to detect reduced range due to cold (such as the snowflake icon in the app) if they wish to do so.

Lastly this PR fixes a bug in that the battery icon did not reflect Charging status due to a typo that I happened to notice while doing the above.

### CODE REVIEW

**Comment by carleeno** [comment]
@alandtse this test failure is weird, the same tests pass on my local branch, and none of the mock data or tests have changed for `charge_rate` in either this repo or teslajsonpy afaict. What makes it weirder is that 37.3 is almost the km equivalent of 23.2 miles, but it's off by more than a rounding error, so it doesn't seem like it's getting converted somewhere.

```
    async def test_charger_rate_value(hass: HomeAssistant) -> None:
        """Tests charger_rate is getting the correct value."""
        await setup_platform(hass, SENSOR_DOMAIN)
    
        state = hass.states.get("sensor.my_model_s_charging_rate")
>       assert state.state == str(car_mock_data.VEHICLE_DATA["charge_state"]["charge_rate"])
E       AssertionError: assert '37.3' == '23.2'
E         - 23.2
E         + 37.3

tests/test_sensor.py:195: AssertionError
```

Should I just push a noop commit to re-kick the tests and see if it was somehow a fluke? Or do you have an idea of what's causing this?

**Comment by carleeno** [comment]
I saw that I forgot to rebase, maybe that was somehow why...let's see if it passes this time...

**Comment by alandtse** [comment]
I mean that's an odd failure but I really want to avoid pushing commits that cause the tests to fail randomly like that. Is it trying to convert the values?

**Comment by carleeno** [comment]
I'm continuing to dig into this today. Yes for some reason the integration is converting the charge rate from 23.2 mph to 37.3 km/h which is breaking the test. I'm not able to reproduce at all testing locally so I'm using github actions in my own forked repo to try to reproduce and narrow it down.

**Comment by carleeno** [comment]
ok I was able to reproduce this with simply a poetry update from dev and no other changes.

It appears some existing tests fail with the newest version of home assistant. Since it's not related to this change, I'll create a new PR to fix the tests.
For this PR I reverted the poetry update and only updated teslajsonpy.

**Pull request merged**
