### PR TITLE
Match Devices to the same VIN.

### PR DESCRIPTION
**Pull request by Megabytemb**
When we are updating other devices, we need to ensure we do so on the same device on the same car.

Fixes https://github.com/alandtse/tesla/issues/207

### CODE REVIEW

**Comment by rako77** [comment]
thanks for this, I did find that the heated steering wheel switch hasn't been updated to include the vin.
https://github.com/alandtse/tesla/blob/dbd4480a1c4445b610454dbc3ac8e2639bd7611f/custom_components/tesla_custom/switch.py#L38

**Comment by megabytemb** [comment]
Good spot.
Updated.

I'm working on a complete re-write of the entity handing in this component- https://github.com/megabytemb/tesla/tree/tesla-rewrite 
I'll do my best to have complete test coverage to prevent issues like missed params like that.

**Comment by alandtse** [comment]
Thanks. I'll merge and release as soon as I get confirmation this fixes the issue. @rako77

**Comment by rako77** [comment]
Thank you, Confirmed working with my home setup, thank you so much.

**Pull request merged**
