### PR TITLE
fix: make destination location unknown after arrival

### PR DESCRIPTION
**Pull request by InTheDaylight14**
closes https://github.com/alandtse/tesla/issues/455

### CODE REVIEW

**Comment by alandtse** [comment]
We should really have a test that exposes what this fixed.

**Comment by alandtse** [comment]
I'd like to add this to the next release and push out a release now that the 2023 beta is out. Any chance you can update your two today?

**Comment by InTheDaylight14** [comment]
Yeah no problem

**Comment by InTheDaylight14** [comment]
> I'd like to add this to the next release and push out a release now that the 2023 beta is out. Any chance you can update your two today?

I think we are good on both now

**Pull request merged**
