### PR TITLE
fix: Improve a couple of things in MQTT sync from Teslamate

### LINKED ISSUE #689: MQTT boolean conversion issue
## Configuration
Teslamate MQTT

## Describe the bug
Boolean entities are not updated correctly from MQTT (e.g. sentry mode, is_climate_on). I think it's due to ReceiveMessage returning msg.payload as a string, which is then casted to bool. But this doesn't work since bool("false") or even bool("False") always returns True.

### PR DESCRIPTION
**Pull request by cguedel**
Fixes #689

- parse boolean strings for is_climate_on, locked, sentry_mode
- add sync for plugged_in
- add sync for charge_port_door_open
- add sync for trunk_open
- add sync for frunk_open
- add sync for is_user_present
- add sync for is_preconditioning

### CODE REVIEW

**Comment by alandtse** [comment]
Thanks. I think the test failure may be unrelated but there's some lint issues. Can you please address?

**Comment by cguedel** [comment]
Should be ok now I think, no idea about the tests though

**Comment by oakedcorn** [comment]
Thanks for the fix!
There's a typo in the code here:

```
def cast_trunk_open(val: str) -> int:
    """Convert bool string to trunk/frunk open/close value."""
    return 255 if cast_bool(str) else 0
```

cast_bool(str) should be cast_bool(val)

**Comment by cguedel** [comment]
Sorry about that, I'll take care of today

**Comment by oakedcorn** [comment]
No worries, thanks for supporting this great integration!

**Pull request merged**
