### PR TITLE
fix: Bump teslajsonpy to fix charge current

### PR DESCRIPTION
**Pull request by Bre77**
A fix to the set charge current function was made in the upstream library, and so a bump is required to fix https://github.com/alandtse/tesla/issues/479

### CODE REVIEW

**Comment by alandtse** [comment]
No need to edit the changelog as that is handled by semantic release. Please bump project.toml and update poetry.

**Comment by alandtse** [comment]
Did you manually edit poetry.lock? You need to run `poetry lock` or `poetry update`. There's a hash it updates to be consisnent.

**Comment by Bre77** [comment]
I'm unfamiliar with poetry and it's throwing lots of errors and trying to change multiple package versions on my Windows machine. I think I convinced it to just update the lock file content hash now.

If this still isn't correct, I'd suggest rejecting this PR and bumping using your existing development environment.

**Comment by garethcook** [comment]
Still failing for me, reverting a backup

**Pull request merged**
