### PR TITLE
docs(grammatical): correct typos and improve grammar

### PR DESCRIPTION
**Pull request by nitin-pandita**
This pull request addresses and corrects grammatical and spelling errors throughout the codebase to improve code readability.
The changes include fixing typos, punctuation, and ensuring proper sentence structure without introducing functional modifications.
These updates are intended to enhance the quality of documentation and code comments.
The focus is on making the codebase more polished and user-friendly by eliminating language-related issues.

### CODE REVIEW

**Comment by nitin-pandita** [comment]
@joestump please have a look at this pull request and merge it. Thank you

**Comment by AbhineshJha** [comment]
@alandtse

**Comment by nitin-pandita** [comment]
> @alandtse

Hi sir can you please merge this pull request

**Comment by skipishere** [comment]
> > @alandtse
> 
> Hi sir can you please merge this pull request

You really don't need to ping people, it'll be reviewed when they have time.

**Pull request merged**
