### PR TITLE
feat: Add Shift State Sensor

### PR DESCRIPTION
**Pull request by Megabytemb**
Add a car Shift state ENUM sensor, so you can detect what gear the car is in specifically.

This is different to the Parking Break binary sensor, as you get the explicit gear.

### CODE REVIEW

**Comment by alandtse** [comment]
Wait, isn't an enum an input class in HA?

**Comment by Megabytemb** [comment]
I got it from the Sensor Dev site

https://developers.home-assistant.io/docs/core/entity/sensor/

"
The sensor has a limited set of (non-numeric) states. The options property must be set to a list of possible states when using this device class.
"

**Comment by alandtse** [comment]
Ok, does our minimum version of ha cover this sensor or would we need to increment it. It's the hacs.json.

**Comment by Megabytemb** [comment]
Looks like it was introduced in 2023.1.0

shall we bump the min version required? or remove the fancy enum stuff and just use a generic sensor?

**Comment by alandtse** [comment]
We can bump.

**Comment by alandtse** [comment]
Oh, can you please make the bump so I can merge this in?

**Comment by Megabytemb** [comment]
Bumped :)

**Comment by alandtse** [comment]
Thanks. But I thought you said it came in in 2023.1? The way to tell is finding the commit that brought it in.

**Comment by Megabytemb** [comment]
Right you are. Fixed

**Pull request merged**
