### PR TITLE
Arallsopp update switch

### PR DESCRIPTION
**Pull request by arallsopp**
Relates to Issue #22 

## Straightforward changes:

- the icon for 'update switch' from mdi:update to mdi:car-connected.
- the text 'seconds between scans' to 'seconds between polling'.

## More complicated:
I think I've also changed the name and ID of the update switch so that it appears as 'polling switch' in the UI and logs. I'm wondering if that's actually a breaking change, as potentially people have automations or scripts that might target the update switch entity.

### CODE REVIEW

**Comment by arallsopp** [comment]
@alandtse, if the breaking change is a pain, feel free to omit [commit 6f1e598](https://github.com/arallsopp/tesla/commit/6f1e59833823c666e3305af9872e5ba419f46fea) from this pull request.

**Comment by alandtse** [comment]
Thanks! I want to get us moved to our final login scheme but I'll plan to get this in when we do that. It will be a breaking change because of the switch rename but it'll make sense since we'll be making some major changes.

**Comment by arallsopp** [comment]
Excellent. Thanks for the update.

This integration saved my bacon last night, btw, as we'd left our car charging at a free pod point whilst grocery shopping, and an automation clocked we'd forgotten it at 11pm. That would have been a very bad start to this morning's commute :)

**Comment by alandtse** [comment]
Merged in by #30

**Comment by arallsopp** [comment]
Thanks, @alandtse. Hope it's helped.

**Pull request closed without merging**
