### PR TITLE
fix: bump teslajsonpy to 3.10.3 (#919)

### PR DESCRIPTION
**Pull request by gkwok1**

### CODE REVIEW

**Comment by alandtse** [comment]
Thanks. Are you able to run poetry update so it syncs the lock file?

**Comment by alandtse** [comment]
Unfortunately whatever fixes were included here appear to have broken the battery tests. Those will need to be fixed before it gets merged.

**Comment by gkwok1** [comment]
Removed the energy_left from the test data and updated the data calculation. Should be good to now.

**Comment by alandtse** [comment]
I mean unless the test isn't needed anymore because it's not in the API, removing a failing test isn't the way to address it. Can you please confirm you removed it because it's not in the API?

**Comment by gkwok1** [comment]
I removed the energy left elements from the mock data and kept the test. The test is now using the same formula as what is used teslajsonpy.

**Pull request merged**
