### PR TITLE
fix: bump teslajsonpy to 3.10.2 (#860)

### PR DESCRIPTION
**Pull request by kbrint**

### CODE REVIEW

**Comment by alandtse** [comment]
Please bump the other references too

**Comment by kbrint** [comment]
Looking back at the last bump (1ae79e7171), I guess this would mean:
* `pyproject.toml`
* `scripts/setup`
* `poetry.lock` (with a bunch of unrelated changes)
* `.pre-commit-config.yaml1 (entirely unrelated changes?)

Should I preserve the unrelated changes that come up, or surgically only commit the changes relatively to teslajsonpy?

**Comment by alandtse** [comment]
Poetry.lock is updated via poetry update. Rest are manual based on version.

**Comment by kbrint** [comment]
I think the latest push has all the requisite changes.  Thanks.

**Review by alandtse — APPROVED** [review]
Awesome. Thanks!

**Pull request merged**
