### PR TITLE
Improve documentation

### PR DESCRIPTION
**Pull request by arallsopp**
I've updated the basic documentation in readme.md to include details of functionality and usage, based upon the text that was present in HA before the integration was stripped, to satisfy Issue #65.

I've then reworked sections of it to reflect the change from scan to polling (PR #30).

### CODE REVIEW

**Comment by arallsopp** [comment]
Hey @alandtse,

I realise it was your intention that this would be added to the wiki, but putting it on the readme gives people a chance to view it within HACS. As the documentation expands, we can link the wiki to more detailed pages if required.

Hope that's ok?

**Comment by alandtse** [comment]
Actually, HACS reads from info.md if that's the reasoning. I'm actually indifferent to wiki vs docs. Wiki isn't gated by PRs so is why I suggest that. My hope is having less friction will encourage participation.

**Comment by arallsopp** [comment]
I get you. It makes sense to use the wiki if you feel people are more likely to add to it there.

Re info.md, apologies. I'm not too familiar with creating integrations. When I follow the 'documentation' link in HACS, it just takes me to https://github.com/alandtse/tesla, hence my suggesting adding it to that page. 

Happy to help, and can put it anywhere you see fit, to be honest. You do great work!

**Comment by alandtse** [comment]
Oh that's right. But on the page where you choose the integration in HACS, it reads from info. It's fine in readme because they're likely not looking at the HACS page anymore. I appreciate your help!

**Comment by arallsopp** [comment]
Glad to be able to assist. Thanks for the merge.

**Pull request merged**
