### PR TITLE
feat: minutes-to-arrival-attribute

### LINKED ISSUE #656: [Feature Request] Provide active_route_minutes_to_arrival directly
**Is your feature request related to a problem? Please describe.**

See https://www.reddit.com/r/homeassistant/comments/14qepmu/comment/jqmore7/?context=3

> I'm using HACS + [Tesla Custom Integration](https://github.com/alandtse/tesla) and it worked gratefully for Charge-on-sun feature. But doing a simple automation as "When Tesla goes home, cast tts in how many time" is hard as hell.(+ when arrival time is less than 2 min, cast tts "Tesla is approaching")
> 
> Here's why:
> 1/ Tesla API give drive_state.active_route_minutes_to_arrival BUT [alandtse use it to create an arrival datetime](https://github.com/alandtse/tesla/blob/dev/custom_components/tesla_custom/sensor.py#L678C22-L678C54)
> 2/ So this value "doesn't exist" on HA side and I have to recreate it myself
> 3/ [Why the f4ck comparing datetime with offset is so hard it can fill at least a whole google page search](https://www.google.com/search?q=home+assistant+compare+two+date&rlz=1C1ONGR_frFR1064FR1064&oq=home+assistant+compare+two+date&gs_lcrp=EgZjaHJvbWUqBggAEEUYOzIGCAAQRRg70gEIMjQ3OWowajSoAgCwAgA&sourceid=chrome&ie=UTF-8)
> 4/ Comparing is not enough, I need to get minutes remaining from this given date

**Describe the solution you'd like**
Provide the value of active_route_minutes_to_arrival as entity or attribute so it can be used directly in action

**Describe alternatives you've considered**
This one :( 
image

**Additional context**
I think I know why it has been done this way: This value is useless as it will not update itself between each tesla API call.

Maybe we could provide our own computed active_route_minutes_to_arrival ? with an event each minute and update it on each API call?

### PR DESCRIPTION
**Pull request by InTheDaylight14**
closes #656

### CODE REVIEW

**Comment by alandtse** [comment]
Wait, didn't we already have arrival time eta?

**Comment by InTheDaylight14** [comment]
Yes, in the format of a timestamp. This is adding the raw "minutes to arrival" from the api and to the attributes of the timestamp sensor as requested in the issue. This will make it easier for ppl to trigger automations on the arrival time dropping below 5 min or similar. There is a workaround posted in the issue for a custom template sensor that does the same thing.

**Comment by alandtse** [comment]
The sensor seems redundant. Would it solve the problem by just doing the attribute only? HA basically requires timers to be timestamps. I don't think we should be encouraging an alternative paradigm.

**Comment by storm1er** [comment]
I think the attribute would be enough, no need to create a full entity for this.

**Pull request merged**
