### PR TITLE
chore: Update manifest.json - bumped teslajsonpy version to latest

### PR DESCRIPTION
**Pull request by mcc05**
bumped teslajsonpy version to latest, to fix powerwall control issues #832 for next pending release 3.19.6

### CODE REVIEW

**Comment by skipishere** [comment]
@alandtse think this is ready to merge if you're happy?

**Review by sevrinrobstad — APPROVED** [review]

**Comment by skipishere** [comment]
Looking at a previous PR to update `teslajsonpy` (https://github.com/alandtse/tesla/commit/49d1c22f8f87a3a6003eee5b5ddfd05a7f2897c5) it looks like you also need to update 
- [pyproject.toml](https://github.com/alandtse/tesla/blob/b5efbaa419febecabc99d7ac1e832b89538227aa/pyproject.toml#L10) 
- [scripts/setup](https://github.com/alandtse/tesla/blob/b5efbaa419febecabc99d7ac1e832b89538227aa/scripts/setup#L13)

**Comment by mcc05** [comment]
Ok done

**Comment by skipishere** [comment]
Looks like it might have been done on a different branch/pr. You'll want to do them all in the same PR. Also (this is all new to me as well) will need to update the `poetry.lock` file by running `poetry update` (from  https://github.com/alandtse/tesla/pull/772#issuecomment-1807278663)

**Comment by mcc05** [comment]
Ok now I'm stuck, don't want to balls things up on poetry.lock TBH no idea what I'm doing with that not familiar with it at all :(

**Comment by alandtse** [comment]
It needs to be done with `poetry update`. It can't be manual.

**Comment by mcc05** [comment]
Ok @alandtse sorry I don't have this setup as a build environment, hence probably more of a hindrance than a help sorry!

**Comment by alandtse** [comment]
Ok, went ahead and did a formal bump

**Comment by alandtse** [comment]
Thanks though.

**Pull request closed without merging**
