### PR TITLE
fix: Bump teslajsonpy to 3.9.7

### LINKED ISSUE #756: Beginning with 2023.38, location tracking fails
Beginning with 2023.38, Tesla introduced controls on location sharing. Location information now requires an approval grant from within the vehicle.

Relevant information can be found in the [vehicle_data endpoint](https://developer.tesla.com/docs/fleet-api#vehicle) in the Fleet API doc:

_For vehicles running firmware versions 2023.38+, location_data is required to fetch vehicle location. This will result in a location sharing icon to show on the vehicle UI._

### PR DESCRIPTION
**Pull request by dagstuan**
Supply 'endpoints'-parameter to 'vehicle_data' endpoint which fixes the missing location data after upgrading vehicles to 2023.38.*

The changes in teslajsonpy should probably be tested some more, I have not tested that this doesn't break any existing logic.

Should hopefully fix #756 and #766

### CODE REVIEW

**Comment by alandtse** [comment]
Poetry also needs to be updated. See other commits with bumps.

**Comment by Zappo-II** [comment]
FYI: Just bumping teslajsonpy did not fix it (#756) for me, seems like even more sensors besides location data get broken then...

**Comment by dagstuan** [comment]
Okay @alandtse I attempted to upgrade for Poetry as well. Though I have never used it before so I might have done something wrong.

**Comment by dagstuan** [comment]
I noticed while I was driving that the sensors in HA would become "unavailable". Turns out that without URL encoding the semicolons the Tesla API sometimes do not return all of the requested data. So this PR in teslajsonpy will probably need to be merged first: https://github.com/zabuldon/teslajsonpy/pull/437

**Pull request merged**
