### PR TITLE
fix: #326 Replace deprecated code

### PR DESCRIPTION
**Pull request by zestysoft**
Tested in HA 2022.11.2 container -- no errors in logs, and I can see things like temp correctly for the vehicle.

### CODE REVIEW

**Comment by alandtse** [comment]
Thanks. Can you please check when this new terminology was introduced in HA and whether we need to bump our minimum supported version?
https://github.com/alandtse/tesla/blob/dev/hacs.json#L4

**Comment by zestysoft** [comment]
Looks like the change was just made in 2022.11.2:  https://github.com/home-assistant/core/commit/67d1dde69fbacf33f2c39ea14d89f2afa425ed18

**Comment by alandtse** [comment]
Actually, it was 2022.11.0. You can expand the list to see and it looks like it came in via the beta.
image

**Comment by alandtse** [comment]
Don't forget to `poetry update` after changing pyproject. We need the lock file committed too.

**Comment by zestysoft** [comment]
Can `poetry update` and the lock file updates be a github action?

**Comment by alandtse** [comment]
> Can `poetry update` and the lock file updates be a github action?

Maybe. But that updates all dependencies so not sure I want that done without some human testing.

**Comment by zestysoft** [comment]
I was thinking the action would only run during the PR process?  Like before the merge and before the automated tests. A human could still pull the rip cord before the merge?

**Comment by alandtse** [comment]
Happy to consider a PR for the automation. Regardless, this specific PR will probably hold until more people adopt 2022.11 and we actually get closer to the deprecation date.

**Comment by alandtse** [comment]
As we're getting closer to the cutoff, I'll plan to merge this in soon.

**Comment by alandtse** [comment]
Ok, just pushed a new release. Next release will include this. I'll plan for probably after xmas.

**Pull request merged**
