### PR TITLE
feat: add time to full charge sensor

### PR DESCRIPTION
**Pull request by InTheDaylight14**
closes https://github.com/alandtse/tesla/issues/348

### CODE REVIEW

**Comment by alandtse** [comment]
Can you look at the change in the request please? He wants an actual sensor now since we already have an attr.

**Comment by InTheDaylight14** [comment]
Kills me that I can't figure out how to run the tests locally. Am I supposed to do a ```poetry install``` or something similar?

**Comment by alandtse** [comment]
> Kills me that I can't figure out how to run the tests locally. ~Am I supposed to do a `poetry install` or something similar?~ No package updates from that command.

```bash
poetry install
poetry run pytest
```

**Comment by alandtse** [comment]
I'd like to merge this in this weekend. Please see if you can close the open question if you can.

**Comment by alandtse** [comment]
This basically good to merge?

**Comment by alandtse** [comment]
Nevermind, just saw your comment in the issue.

**Pull request merged**
