### PR TITLE
refactor: reduce code needed to construct entities

### PR DESCRIPTION
**Pull request by bdraco**

### CODE REVIEW

**Comment by alandtse** [comment]
Thanks. Just to confirm, you've marked this as fix. But does it actually solve a bug or issue? Or was it just to clean up code.

**Comment by bdraco** [comment]
Its just code cleanup. Intent was to generate a release

**Comment by alandtse** [comment]
I think our ci settings only generate a release on feat or bug. I'll see if I can tweak it for perf and refactor too. Didn't you solve a wake issue? Pulling in the new dependency may count as a fix.

**Comment by bdraco** [comment]
> I think our ci settings only generate a release on feat or bug. I'll see if I can tweak it for perf and refactor too. Didn't you solve a wake issue? 


> Pulling in the new dependency may count as a fix. 


https://pypi.org/project/teslajsonpy/

It looks like the publish failed

**Comment by alandtse** [comment]
Thanks. Fixed the pypi publish. 3.9.2

**Pull request merged**
